### PR TITLE
Mysql2Makara support

### PR DESCRIPTION
**Pull request by bf4**
Perhaps we should make it easier to add behavior like this outside of a fork via template method?

### CODE REVIEW

**Comment by jkowens** [comment]
Could `postgresql_makara` support be added in with this PR too?

**Comment by jkowens** [comment]
I noticed there is also PR #204 that uses another method of creating a proxy adapter. @zdennis which way is preferred?

**Comment by zdennis** [comment]
I prefer what @bf4 has here. If we can re-use an existing adapter as-is might as well. It's easy enough to break out if the functionality ever needs to be customized.

We should make sure that we add this to https://github.com/zdennis/activerecord-import/blob/master/Rakefile#L16 and https://github.com/zdennis/activerecord-import/blob/master/.travis.yml#L40 so the test suite runs against it.

**Comment by zdennis** [comment]
Thanks @bf4 and @jkowens. I made some updates locally and merged into master in c7424fd

**Comment by bf4** [comment]
Yay!

**Pull request closed without merging**
