### PR TITLE
Support uuid primary keys

### LINKED ISSUE #311: Support non-integer primary keys
I'm using UUID's are my primary key. Whenever I run an import my id's disappear. I believe this is because you are expecting the primary key to be an integer.

I believe this is the line that's causing the issue:

https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L534

### PR DESCRIPTION
**Pull request by jkowens**
Resolves #311 and the issue that #138 has evolved into.

### CODE REVIEW

**Comment by steventen** [comment]
The fix looks good to me. I've run my previous failed tests against this branch and they pass.

Thanks!

**Comment by anthonator** [comment]
👍 looks good to me!

**Comment by jkowens** [comment]
@zdennis do you think this could be merged into master? I have another update that could make use of some of this work. Trying to take advantage of Hacktoberfest! 😄

**Comment by zdennis** [comment]
@jkowens, I added you as a collaborator. Want to give it a go on this PR to make sure I pushed the right button? :)

**Comment by jkowens** [comment]
Looks like I'm good to go! 👍

**Pull request merged**
