### PR TITLE
Use prepend pattern for ActiveRecord::Base#establish_connection patching

### PR DESCRIPTION
**Pull request by dombesz**
This PR fixes the issue mentioned in the #647 .

### CODE REVIEW

**Comment by jkowens** [comment]
Thanks for supplying a PR for this issue. Are you able to investigate why the AR 4.0 tests fail? I'm ok officially dropping support for 3.2.

**Comment by dombesz** [comment]
Yes, I will provide fixes for the failing tests.

**Comment by dombesz** [comment]
@jkowens I fixed the issues. Please check it out. Thanks!

**Comment by jkowens** [comment]
This simplicity of this change is beautiful 💯

**Comment by jkowens** [comment]
This has been released in v1.0.4 🎉

**Pull request merged**
