### PR TITLE
Work with Activerecord 5.0.0

### PR DESCRIPTION
**Pull request by zdennis**
Work in progress for getting activerecord-import to work with ActiveRecord 5.0.0 / Rails 5.0.0

Related to issue #222 .

### CODE REVIEW

**Comment by zdennis** [comment]
[em-synchrony](https://github.com/igrigorik/em-synchrony) is not ActiveRecord 5.0.x compatible so that adapter currently fails, but all other adapters successfully pass all tests for compatibility.

With that in mind I'm merging this in order to release an update for those waiting on ActiveRecord 5.0.x compatibility.

**Comment by zdennis** [comment]
This was just released in activerecord-import 0.11.0 gem.

**Comment by walf443** [comment]
Can you push tag for v0.11.0?

**Comment by zdennis** [comment]
Done. Thanks @walf443

**Pull request merged**
