### PR TITLE
Test JDBC drivers on JRuby

### PR DESCRIPTION
**Pull request by sferik**
Does what it says on the tin.

### CODE REVIEW

**Comment by sferik** [comment]
Looks like this tests passed on Travis CI!

**Comment by zdennis** [comment]
Nice @sferik! Care to rebase and re-push?

**Comment by sferik** [comment]
@zdennis Rebased and pushed.

**Comment by zdennis** [comment]
Sorry for the wait on this @sferik, this has been merged in now.

**Pull request closed without merging**
