### PR TITLE
Remove deprecated use of `alias_method_chain` in Rails 5

### LINKED ISSUE #270: Use of alias_method_chain has been depreciated in Rails 5
This is my first time using Github / commenting on a project, so forgive me if I've made a mistake, but while upgrading my Rails 4.2 app to Rails 5, I've encountered a depreciation warning related to activerecord-import's use of `alias_method_chain` found in lib > activerecord-import.rb.

As detailed here in [Riding on Rails](http://weblog.rubyonrails.org/2015/3/27/this-week-in-rails-goodbye-alias_method_chain-postgresql-typecasting-and-more/), and here in this Rails pull [request 19434](https://github.com/rails/rails/pull/19434), `alias_method_chain` has been depreciated in favor of Module.prepend. I've [looked into](http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/) offering up a fix using Module.prepend, but I'm afraid I'm just not knowledgeable enough in Ruby.

### PR DESCRIPTION
**Pull request by codeodor**
This would close #270

### CODE REVIEW

**Comment by codeodor** [comment]
Hold off on merging this. All the tests pass for me, but when using it in my app's tests, we get infinite recursion on establishing a connection.

**Comment by codeodor** [comment]
Well, running it in dev mode it works fine, and even running the single failing test works fine. So this is might take a while to run down.

**Comment by codeodor** [comment]
Ok, after some research, I could not figure out what was going wrong, so I switched gears and just used `alias_method`.

It should be safe now. 😁

**Comment by zdennis** [comment]
This is going out in the 0.14.0 release.

**Pull request merged**
