### PR TITLE
Use consistent spacing and styling

### PR DESCRIPTION
**Pull request by sferik**
@zdennis I’ve made a point of making each style change in a discrete commit, so you can cherry-pick only the commits you like, in case there are any you disagree with. If you prefer, let me know which of these commits you want me to remove from this pull request and I will rebase with those commits deleted.

You may want to use the new [commit-by-commit workflow](https://github.com/blog/2123-more-code-review-tools#more-flexible-review) to review these changes.

### CODE REVIEW

**Comment by zdennis** [comment]
I'll hold off merging any other commits right now if you want to update this PR and then I'll merge this in. This code-base has existed for 10 years (before it was called ar-extensions) so I really appreciate a broad stroke to bring things back to consistency and modern idiomatic ruby.

**Comment by sferik** [comment]
I’ll rebase now.

**Comment by sferik** [comment]
@zdennis Okay, rebased.

**Comment by zdennis** [comment]
Thanks @sferik !

**Pull request merged**
