### PR TITLE
Add Hstore support

### PR DESCRIPTION
**Pull request by ghiculescu**
Adds support for Rails 4 Postgres Hstores.

With Hstores, calling `#{name}_before_type_cast` always returns an empty string (I haven't dug in enough to find out why), but calling `name` directly returns a hash, which is then transformed into an insert statement correctly in the `values_sql_for_columns_and_attributes` method.

If the user isn't using Postgres or there are no Hstore columns, they won't even notice the difference.

I wasn't able to get the tests running (the MySQL gem wouldn't install and I don't really care to work out why) but I have this running successfully in my project. That said it is probably worth adding tests if anyone else is able to do so.

### CODE REVIEW

**Comment by leonardvandriel** [comment]
Hi, I can confirm this issue. This fix works from me too, thanks. Any plans on merging?

**Comment by brodock** [comment]
:+1:

**Comment by jkowens** [comment]
Hstore columns are currently supported, it's just that the accessors are not. When importing, the entire hash value for the store must be set:

```
Model.new(my_store: {my_attr: 'test'}) # works
Model.new(my_attr: 'test') # attribute will not be saved
```
See #150.

Besides `hstore` there is `jsonb` as well as `text` that can contain serialized data. Is there a way to make this a more complete solution? Are there performance tradeoffs that need to be considered? Setting store values using a hash doesn't seem like it would necessarily be that much more trouble.

**Comment by mparodi** [comment]
The same happens for JSONB columns! I would change one of your lines of the suggested marge like this:

```
if columns_hash.has_key?(name) && [:hstore, :jsonb].include?(columns_hash[name].type)
```

I hope to see this on the next version of activerecord-import!

**Comment by jkowens** [comment]
Replaced by #322.

**Pull request closed without merging**
