### PR TITLE
return the ids from a bulk insert [postgres only]

### PR DESCRIPTION
**Pull request by robmathews**
A common request is to return the ids from the newly created object. This patch does that. It's postgres only, but at least it doesn't break for non-postgres databases - it just doesn't set the id. 

The api is unchanged. Instead, for every model that was saved, it sets the :id and marks the record clean, so that you can keep using it if you want.

Seems like one could pretty easily do a BFS on the changed associations and bulk-import the next level down in the tree in one sql statement as well .. at least for postgres.

Let me know if this is any use to you; works fine for us, and that's all I need.

### CODE REVIEW

**Comment by alainmeier** [comment]
This is an excellent PR, will this be merged?

**Comment by zdennis** [comment]
@alainmeier, it will become much more likely if it's become merge-able and stays green.

**Comment by johnnaegle** [comment]
I've rebased the commits onto the latest master and got the tests working under mysql, postgresql and sqlite3.  The branch is here: https://github.com/GoodMeasuresLLC/activerecord-import/tree/set_ids_in_bulk_import.  I will open a PR from that branch when I think it is ready, but some early feedback would be helpful.

**Comment by johnnaegle** [comment]
See #178

**Comment by koheisg** [comment]
Why don't you close? it seems to be resolved for me.

**Comment by zdennis** [comment]
Thanks for following up @koheisg, closing now.

**Pull request closed without merging**
