### PR TITLE
Prepping 0.14.0 release

### PR DESCRIPTION
**Pull request by zdennis**
- [x] bump version
- [x] update changelog
- [x] tag
- [x] reorder commits so version is the last
- [ ] push to rubygems

### CODE REVIEW

**Comment by zdennis** [comment]
@sferik  / @jkowens, I'm prepping a 0.14.0 release for tomorrow night or Friday. Is there anything else you'd like to see go out in the 0.14.0 release? 

And thank you both so much for your help these past few months!

**Comment by jkowens** [comment]
@zdennis I'm happy with what you've got for the 0.14.0 release. I'm not sure if you'd want to consider #276 for this one?

**Comment by sferik** [comment]
👍 from me to ship 0.14.0.

**Comment by zdennis** [comment]
@jkowens, #276 is now in!

**Comment by zdennis** [comment]
Pushed to [ruby gems](https://rubygems.org/gems/activerecord-import)!

**Pull request merged**
