### PR TITLE
Add postgresql_makara_adapter

### PR DESCRIPTION
**Pull request by ptrln**
This adds support for MakaraPostgreSQLAdapter.

### CODE REVIEW

**Comment by zdennis** [comment]
@ptrln, where can I find the `postgresql_makara` adapter? I don't see any makara gems doing a `gem search -r makara`

**Comment by ptrln** [comment]
We're using the `makara` gem with PG, which includes the adapter here: https://github.com/taskrabbit/makara/blob/master/lib/active_record/connection_adapters/makara_postgresql_adapter.rb

**Comment by zdennis** [comment]
Just noting that when we pull this in we're going to update this to follow conventions in https://github.com/zdennis/activerecord-import/pull/274 and to also make sure  https://github.com/zdennis/activerecord-import/blob/master/Rakefile#L16 and https://github.com/zdennis/activerecord-import/blob/master/.travis.yml#L40 are updated so the test suite runs against it.

**Comment by zdennis** [comment]
Thanks @ptrln ! I pulled merged this into master in 8ee0133

**Pull request closed without merging**
