### PR TITLE
Recursively import all has_one/has_many associations

### PR DESCRIPTION
**Pull request by zdennis**
Based on @sferik's work in PR #230

### CODE REVIEW

**Comment by zdennis** [comment]
Closing this in favor of #243 which builds on this PR. Thanks @sferik.

**Comment by zdennis** [comment]
This has been included in the [0.12.0](https://rubygems.org/gems/activerecord-import/versions/0.12.0) release.

**Comment by sferik** [comment]
:+1:

**Comment by rhannequin** [comment]
Hello,

First, thank you very much for this gem, it is **much** appreciated every day from casual to complex data imports.

I am having troubles with the multi-level feature, when trying to import models with associations. I tried to follow the [multi-level example](https://github.com/zdennis/activerecord-import/wiki#multi-level-example) this way:

I created a blank app with two models:

```
$ bundle exec rails g model Book title:string
$ bundle exec rails g model Review name:string book:references
```

Then I added the association to the `Book` model:

```ruby
class Book < ActiveRecord::Base
  has_many :reviews
end
```

I created a basic rake task with the same code as the example, to insert books with one review in each, and checking at the end if everything went good:

```ruby
task test: :environment do
  Book.delete_all
  Review.delete_all

  books = []
  10.times do |i|
    book = Book.new(title: "Book ##{i}")
    book.reviews.build(name: "Review ##{i}")
    books << book
  end
  Book.import books, recursive: true

  puts "'Book' records count: #{Book.count}"
  puts "Last 'Book' reviews count: #{Book.last.reviews.count}"
  puts "'Review' records count: #{Review.count}"
end
```

What I have in return shows that the books were inserted but not the associated reviews:

```
'Book' records count: 10
Last 'Book' reviews count: 0
'Review' records count: 0
```

I don't know if my way of inserting associated models in database is wrong or if the multi-level feature has an issue, I thought it was the best place to warn about this behaviour has @sferik 's PR (thank you for that btw) was supposed to fix it.

This test was run on Ubuntu 15.10 with:
* `rails` v4.2.5.1
* `activerecord` v4.2.5.1
* `sqlite3` v1.3.11
* `activerecord-import` from Github (at master@df866a4)

Thank you.

**Pull request merged**
